config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :invoices, only: [:index, :create, :update, :show] do
    get 'expenses', on: :collection
    get 'counts', on: :collection
    get 'finalize', on: :member
  end
  resources :counts, only: :new

  resources :flats
  resources :residents
  resources :users, only: [:update]
  resources :meters

  # resources :invoice_details

  root 'invoices#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/meter.rb
class Meter < ApplicationRecord
  belongs_to :flat, optional: true
  belongs_to :parent, class_name: 'Meter', optional: true
  has_many :counts
  accepts_nested_attributes_for :counts

  enum expense_type: [:kaltwasser, :warmwasser, :heizung, :strom, :gas, :warmwasser_gesamt]
  validates_presence_of :initial_count, :expense_type

  scope :by_user, lambda {|user_id| where(user_id: user_id)}

  def count_at(date)
    counts.where(date: date).sum {|c| c[:amount]}
  end

  def find_or_initialize_counts(invoice_id)
    if counts.length == 0
      return Array.new.push(counts.find_or_initialize_by(meter_id: id, invoice_id: invoice_id))
    end
    counts.where(invoice_id: invoice_id)
  end
end

app/controllers/meters_controller.rb
class MetersController < ApplicationController
  before_action :set_meter, only: [:edit, :update, :destroy]

  def index
    @meters = Meter.where(user_id: current_user.id)
  end

  def new
    @meter = Meter.new
  end

  def edit
  end

  def create
    @meter = Meter.new(meter_params)
    @meter.user_id = current_user.id

    respond_to do |format|
      if @meter.save
        format.html { redirect_to meters_path, notice: 'Der Zähler wurde erstellt.' }
        format.json { render json: @meter, status: :created }
      else
        format.html { render :new }
        format.json { render json: @meter.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @meter.update(meter_params)
        format.html { redirect_to meters_path, notice: 'Der Zähler wurde aktualisiert.' }
        format.json { render json: @meter, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @meter.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @meter.destroy
    respond_to do |format|
      format.html { redirect_to meters_url, notice: 'Der Zähler wurde gelöscht.' }
      format.json { head :no_content }
    end
  end

  private
    def set_meter
      @meter = Meter.find(params[:id])
    end

    def meter_params
      params.require(:meter).permit(:name, :flat_id, :expense_type, :initial_count)
    end
end

app/helpers/meters_helper.rb
module MetersHelper
end

app/views/meters/_form.html.erb
<%= form_with(model: meter, local: true, class: 'col-md-4') do |form| %>
  <% if meter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meter.errors.count, "error") %> prohibited this meter from being saved:</h2>

      <ul>
      <% meter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, 'Name' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

    <div class="form-group">
      <%= form.label :flat_id, 'Wohnung' %>
      <%= form.collection_select :flat_id, Flat.by_user(current_user.id), :id, :name, {include_blank: true}, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :expense_type, 'Kostentyp' %>
      <%= form.select :expense_type, Meter.expense_types.keys.map { |t| [t.humanize, t]}, {include_blank: true}, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :initial_count, 'Initialer Zählerstand' %>
      <%= form.text_field :initial_count, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :parent, 'Überzähler' %>
      <%= form.collection_select :parent, Meter.all, :id, :name, {include_blank: true}, class: 'form-control' %>
    </div>

  <%= form.submit 'Speichern', class: 'btn btn-primary' %>
<% end %>

app/views/meters/edit.html.erb
<h1>Zähler bearbeiten</h1>

<%= render 'form', meter: @meter %>

<%= link_to 'Anzeigen', @meter %> |
<%= link_to 'Zurück', meters_path %>

app/views/meters/index.html.erb
<h3>Zähler</h3>

<% if notice %>
    <div id="notice" class="alert alert-success" role="alert"><%= notice %></div>
<% end %>

<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Wohnung</th>
        <th>Kostentyp</th>
        <th>Initialer Stand</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @meters.each do |meter| %>
        <tr>
          <td><%= meter.name %></td>
          <td><%= meter.flat.name unless meter.flat.nil? %></td>
          <td><%= meter.expense_type.humanize %></td>
          <td><%= meter.initial_count %></td>
          <td><%= link_to 'Bearbeiten', edit_meter_path(meter) %></td>
          <td><%= link_to 'Löschen', meter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'Neuer Zähler', new_meter_path %>

app/views/meters/new.html.erb
<h1>Neuer Zähler</h1>
<p><%= link_to 'Zurück', meters_path %></p>

<%= render 'form', meter: @meter %>