config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :invoices, only: [:index, :create, :update, :show] do
    get 'expenses', on: :collection
    get 'counts', on: :collection
    get 'finalize', on: :member
  end
  resources :counts, only: :new

  resources :flats
  resources :residents
  resources :users, only: [:update]
  resources :meters

  # resources :invoice_details

  root 'invoices#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/resident.rb
class Resident < ApplicationRecord
  belongs_to :flat
  belongs_to :user

  validates_presence_of :persons, :flat_id, :move_in

  scope :by_user, lambda { |user_id| where(user_id: user_id) }
  scope :current, lambda { where(move_out: nil) }
  scope :of_year, lambda { |year| where("move_in <= ?", Date.new(year, 12, 31)).where("move_out >= ? OR move_out IS ?", Date.new(year, 1, 1), nil) }

  def name
    "#{first_name} #{last_name}"
  end

  def year_share(year)
    ((last_day(year) - first_day(year)) / (leap?(year) ? 366 : 365).to_f)
  end

  def leap?(year)
    if (year % 400) == 0 || ((year % 4) == 0 && (year % 100) != 0)
      return true;
    end

    false
  end

  def usage(expense_type, year)
    flat.meters.where(expense_type: expense_type).sum do |m|
      return (m.count_at(last_day(year)) - m.count_at(first_day(year)))
    end
  end

  def first_day(year)
    first_day = Date.new(year, 1, 1)
    last_day = Date.new(year, 12, 31)

    if(move_in <= first_day)
      return Date.new(year-1, 12, 31)
    elsif move_in > last_day
      return 0
    end

    move_in
  end

  def last_day(year)
    first_day = Date.new(year-1, 12, 31)
    last_day = Date.new(year, 12, 31)
    
    if(move_out.nil? || move_out > last_day)
      return last_day
    elsif move_out < first_day
      return 0
    end

    move_out
  end
end

app/controllers/residents_controller.rb
class ResidentsController < ApplicationController
  before_action :set_resident, only: [:edit, :update, :destroy]

  # GET /residents
  # GET /residents.json
  def index
    @residents = Resident.where(user_id: current_user.id)
  end

  # GET /residents/new
  def new
    @resident = Resident.new
  end

  # GET /residents/1/edit
  def edit
  end

  # POST /residents
  # POST /residents.json
  def create
    @resident = Resident.new(resident_params)
    @resident.user_id = current_user.id

    respond_to do |format|
      if @resident.save
        format.html { redirect_to residents_path, notice: 'Bewohner wurde erstellt.' }
        format.json { render json: @resident, status: :created }
      else
        format.html { render :new }
        format.json { render json: @resident.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /residents/1
  # PATCH/PUT /residents/1.json
  def update
    respond_to do |format|
      if @resident.update(resident_params)
        format.html { redirect_to residents_path, notice: 'Bewohner wurde aktualisiert.' }
        format.json { render json: @resident, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @resident.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /residents/1
  # DELETE /residents/1.json
  def destroy
    @resident.destroy
    respond_to do |format|
      format.html { redirect_to residents_url, notice: 'Der Bewohner wurde entfernt.' }
      format.json { head :no_content }
    end
  end

  private
    def set_resident
      @resident = Resident.find(params[:id])
    end

    def resident_params
      params.require(:resident).permit(:first_name, :last_name, :move_in, :move_out, :flat_id, :persons, :street, :plz, :location, :email)
    end
end

app/helpers/residents_helper.rb
module ResidentsHelper
end

app/views/residents/_form.html.erb
<%= form_with(model: resident, local: true, class: 'col-md-4') do |form| %>
    <% if resident.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(resident.errors.count, "error") %> prohibited this resident from being saved:</h2>

          <ul>
            <% resident.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= form.label :last_name, 'Nachname' %>
      <%= form.text_field :last_name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :first_name, 'Vorname' %>
      <%= form.text_field :first_name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :street, 'Straße, Hausnummer' %>
      <%= form.text_field :street, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :plz, 'Postleitzahl' %>
      <%= form.number_field :plz, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :location, 'Ort' %>
      <%= form.text_field :location, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :email, 'Email' %>
      <%= form.text_field :email, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :persons, 'Anzahl der Personen' %>
      <%= form.text_field :persons, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :move_in, 'Einzugsdatum' %>
      <%= form.date_field :move_in, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= form.label :move_out, 'Auszugsdatum' %>
      <%= form.date_field :move_out, class: 'form-control', placeholder: 'Optional' %>
    </div>
    <div class="form-group">
      <%= form.label :flat_id, 'Wohnung' %>
      <%= form.collection_select :flat_id, Flat.by_user(current_user.id), :id, :name, {include_blank: true}, class: 'form-control'  %>
    </div>

    <%= form.submit 'Speichern', class: 'btn btn-primary' %>
<% end %>

app/views/residents/edit.html.erb
<h1>Editing Resident</h1>

<%= render 'form', resident: @resident %>

<%= link_to 'Show', @resident %> |
<%= link_to 'Back', residents_path %>

app/views/residents/index.html.erb
<h3>Bewohner</h3>

<% if notice %>
    <div id="notice" class="alert alert-success" role="alert"><%= notice %></div>
<% end %>

<hr />

<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Anzahl Personen</th>
        <th>Einzug</th>
        <th>Auszug</th>
        <th>Wohnung</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @residents.each do |resident| %>
        <tr>
          <td><%= resident.name %></td>
          <td><%= resident.persons %></td>
          <td><%= resident.move_in %></td>
          <td><%= resident.move_out %></td>
          <td><%= resident.flat.name %></td>
          <td><%= link_to 'Bearbeiten', edit_resident_path(resident) %></td>
          <td><%= link_to 'Löschen', resident, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'Neuen Bewohner erstellen', new_resident_path %>

app/views/residents/new.html.erb
<h1>Neuen Bewohner erstellen</h1>
<p><%= link_to 'Zurück', residents_path %></p><br />

<%= render 'form', resident: @resident %>