config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :invoices, only: [:index, :create, :update, :show] do
    get 'expenses', on: :collection
    get 'counts', on: :collection
    get 'finalize', on: :member
  end
  resources :counts, only: :new

  resources :flats
  resources :residents
  resources :users, only: [:update]
  resources :meters

  # resources :invoice_details

  root 'invoices#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NkaRails</title>
  <%= csrf_meta_tags %>
  <meta name="turbolinks-cache-control" content="no-cache">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<% if user_signed_in? %>
    <nav class="navbar navbar-inverse navbar-fixed-top ">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Nebenkostenapp</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Abrechnungen', invoices_url %></li>
            <li><%= link_to 'Betriebskosten', expenses_invoices_url %></li>
            <li><%= link_to 'Zählerstände', counts_invoices_url %></li>
            <li><%= link_to 'Bewohner', residents_url %></li>
            <li><%= link_to 'Wohnungen', flats_url %></li>
            <li><%= link_to 'Zähler', meters_url %></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <li>
              <div class="navbar-text">Signed in as <%= current_user.username %></div>
            </li>
            <li>
              <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
<% end %>

<main>
  <div class="container">
    <%= yield %>
  </div>
</main>
</body>
</html>